// import { JSON } from "../..";
import { bs } from "../../custom/bs";
import { serializeArbitrary } from "./arbitrary";
import { serializeArray } from "./array";
import { serializeBool } from "./bool";
import { serializeDate } from "./date";
import { serializeFloat } from "./float";
import { serializeInteger } from "./integer";
import { serializeMap } from "./map";
import { serializeString } from "./string";

export function serialize<T>(src: T): void {
    if (isBoolean<T>()) {
        serializeBool(src as bool);
    } else if (isInteger<T>()) {
        // @ts-ignore
        serializeInteger<T>(src);
    } else if (isFloat<T>(src)) {
        // @ts-ignore
        serializeFloat<T>(src);
        // @ts-ignore: Function is generated by transform
    } else if (changetype<usize>(src) == <usize>0) {
        bs.ensureSize(8);
        store<u64>(bs.offset, 30399761348886638);
        bs.offset += 8;
    } else if (isString<nonnull<T>>()) {
        serializeString(src as string);
        // @ts-ignore: Supplied by transform
    } else if (isDefined(src.__SERIALIZE)) {
        // @ts-ignore
        serializeObject(changetype<nonnull<T>>(src));
    } else if (src instanceof Date) {
        // @ts-ignore
        serializeDate(changetype<nonnull<T>>(src));
    } else if (src instanceof Array) {
        // @ts-ignore
        serializeArray(changetype<nonnull<T>>(src));
    } else if (src instanceof Map) {
        // @ts-ignore
        serializeMap(changetype<nonnull<T>>(src));
    } /*else if (src instanceof JSON.Value) {
        serializeArbitrary(src);
    }*/ else {
        ERROR(`Could not serialize src of type ${nameof<T>()}. Make sure to add the correct decorators to classes.`);
    }
}